### ISSUE TITLE
msg size

### ISSUE THREAD

**Issue by tczaude** [hvisage/metalog#10]
Hi i have problem
My web app send very big msg. metalog truncate this to some around 2000 signs.
How i can increase this limit ?

**Comment by tczaude** [comment]
Problem not exist always is dependency by logger.
Sample example 

php -r 'openlog("myScriptLog", 0, LOG_LOCAL0); syslog(LOG_INFO, str_repeat("x ", 60000));'

metalog truncate to 4096 signs.

**Comment by m-kress** [comment]
Currently you can't configure the length of the log entries. Unfortunatelly they are hardcoded by a define in metalog.h:
#define MAX_LOG_LENGTH 8192U 
So you would have to change that and recompile :-(

**Comment by tczaude** [comment]
Hi 
Thanks for answer. I'am blind :/
Patch and recompile is not problem i use Funtoo :)
i change this value end nothing happend this same result  :(

**Comment by m-kress** [comment]
You are right. Even the buffer[] in process_log() is hard coded. This might be the reason, why the original authors limited it:
https://tools.ietf.org/html/rfc5426#section-3.2

It might be worth a try: 
- Increase the buffer array size
- Increase MAX_LOG_LENGTH to at least the same value like buffer size
- modify the while loop, so it looks like the while loop for the kernel log a few lines below), so it wont overwrite already read data. Use a new variable like bpos to position the next read in the buffer array.

I have no idea, why the syslog read is handled differently than the kernel log read. There must be a reason...

**Comment by m-kress** [comment]
Closed, as mentioned (not as "soon" as originally thought :-)
