### ISSUE TITLE
valid config entries are ignored/broken?

### ISSUE THREAD

**Issue by ghost** [hvisage/metalog#14]
With the following config:
```
# custom metalog configuration

maxsize  = 1048576  # 1 MB
maxtime  = 86400    # 24 hrs
maxfiles = 14

Everything important :

    facility       = "*"
    minimum        = 6
    logdir         = "/var/log/everything"

Errors and other critical conditions :

    facility       = "*"
    minimum        = 3
    logdir         = "/var/log/error"

test :

    program_regex  = "x"
    logdir         = "/var/log/test"

AppArmor messages : # first with break to avoid spamming other logs

    regex          = "apparmor"
    logdir         = "/var/log/apparmor"
    break          = 1

Kernel messages :

    facility       = "kern"
    logdir         = "/var/log/kernel"
    break          = 1

XBPS messages :

    program_regex  = "xbps"
    logdir         = "/var/log/xbps"
    break          = 1
```
metalog behaves as follows:
- 1st entry works
- 2nd entry works
- 3rd entry doesn't work
- 4th entry doesn't work
- 5th entry works
- 6th entry works

I initially thought there is something wrong with my system given the complete randomness of what works and what doesn't, but it turns out I am able to reproduce this behavior in its entirety on a livecd of my Linux distribution (Void GNU/Linux x86_64 base glibc 2019-11-09).

**Comment by m-kress** [comment]
- is there any change, when you add an ^ as a prefix to your regex expression, e.g. facility = "^kern"
- is it wanted, that there is no "break = 1" in the section "test"?
- can you see a pattern, which messages are missing? Are they from a certain regex section or are the missing entries randomly?

**Comment by ofiala-a51** [comment]
> can you see a pattern, which messages are missing? Are they from a certain regex section or are the missing entries randomly?
There isn't really anything missing as anything even just remotely important is caught by the "Everything important" entry, which works. However, some of the entries somehow do not catch any messages. Their log files are never created, despite there being correct entries that should create them. Which ones work and which ones don't is in my original post.

> is it wanted, that there is no "break = 1" in the section "test"?
Yes, this is intentional. I have done this so that everything that gets logged by the "XBPS messages" section should also get logged by the "test" section. Thus, if the "test" section doesn't record anything, it's clearly weirdly broken (which seems to be the case).

> is there any change, when you add an ^ as a prefix to your regex expression, e.g. facility = "^kern"
Well, `facility = "^kern"` is invalid. If I put the `^` into a regex directive, such as `program_regex = "^xbps"`, that section stops working as well. It's possible that this case is just some kind of limitation of metalog's regexes though, which would explain why there are the `neg_regex` and `program_neg_regex` directives. Perhaps @hvisage can clear this up?

**Comment by m-kress** [comment]
Ah - now I understand: with entries you meant the sections. So section test and apparmor don't work.
Unfortunatelly I'm not familiar with the perl regex.

Could you try: 
regex  = "[x]"
I guess, this will will trigger the log, when the log entry matches the x
and: 
program_regex  = "^apparmor"
This will trigger a log entry, when a program name beginning with "apparmor" is logging something.

**Comment by ofiala-a51** [comment]
Thanks for the suggestions, but none of this works either.

**Comment by eth0OS** [comment]
Hello, adding here my piece of info as I share this problem, it might be related to our packges since we both use void-linux.

```
# Sample Metalog configuration file

maxsize  = 1048576  # size in bytes (1048576 = 1 megabyte)
maxtime  = 86400    # time in seconds (86400 = 1 day)
maxfiles = 5        # num files per directory

Metalog : #[DOES NOT WORK]

  program   = "metalog"
  logdir    = "/var/log/metalog"
  break     = 1

Everything important : #[WORKS]

    facility = "*"
    minimum  = 6
    logdir   = "/var/log/everything"

Everything very important : #[DOES NOT WORK]

    facility = "*"
    minimum  = 1
    logdir   = "/var/log/critical"

Password failures : #[WORKS]

    regex    = "(password|login|authentication)\s+(fail|invalid)"
    regex    = "(failed|invalid)\s+(password|login|authentication|user)"
    regex    = "ILLEGAL ROOT LOGIN"
    logdir   = "/var/log/pwdfail"
#    command  = "/usr/local/sbin/mail_pwd_failures.sh"

Kernel messages : #[WORKS]

    facility = "kern"
    logdir   = "/var/log/kernel"
    break    = 1

Crond : #[WORKS]

    facility = "cron"
    logdir   = "/var/log/cron"
    break    = 1

Firefox: #[DOES NOT WORK]
	program_regex = "^firefox"
	logdir = "/var/log/firefox"
	break = 1

Daemon: #[WORKS]
	facility = "daemon"
	logdir = "/var/log/daemon"
	break = 1

XBPS messages : #[WORKS]
    program_regex  = "xbps"
    logdir         = "/var/log/xbps"
    break          = 1
```

**Comment by m-kress** [comment]
Eventually you are right and there is something wrong with the build. Can you compile the lib pcre and metalog from scratch? In case of a live CD it might be possible to mount the lib and the metalog binary via bind over the existing lib and binary? In case you installed it on your hard drive a quick test would be easier.

@eth0OS: Are you running your Void linux from a live CD, too? 
I can offer to send you my compiled binaries that are linked against libc-2.32.

**Comment by eth0OS** [comment]
I'm running on a traditional installation. Looking at the [metalog template](https://github.com/void-linux/void-packages/blob/51fd84fe7469aadeb2b2a024379a4d7590f570c8/srcpkgs/metalog/template), the code that build our packages, I can see our binaries are built against our pcre-devel package which stands in the 8.44 version. Should we try to build it against the PCRE2 (version 10.35) package?

**Comment by m-kress** [comment]
My libprce is also 8.44. I've never use PCRE2. My guess is, that trying couldn't hurt.

**Comment by eth0OS** [comment]
I got it working by running the application I'd like to log with an script piping its output to logger -t 'appname', this way its output is written to syslog and catch by /everything/current, also, I could get the a specific rule for it working with program_regex = appname.

**Comment by m-kress** [comment]
It seams apparmor and the x application don't produce syslog entries, that metalog can interprete.
As you found a solution, would it make sense to close this issue?

**Comment by ofiala-a51** [comment]
I haven't found a solution, and even if I had, I believe the fact that metalog can't interpret these entries and other syslog implementations can is an obvious bug.

**Comment by LoneFox78** [comment]
The real cause of this is, comments in the config file only work on separate lines, and it also silently ignores invalid lines. So, this line doesn't do anything:
```
AppArmor messages : # first with break to avoid spamming other logs
```
and then the options below it become part of the previous entry, breaking it as well.

**Comment by m-kress** [comment]
Thanks LoneFox78! I tested this and it is exacly as you describe.

**Comment by m-kress** [comment]
The text of the section is invalid - it must end with ":" - an appended comment will invalidate the whole section.
