### ISSUE TITLE
metalog doesn't trim trailing newline characters

### ISSUE THREAD

**Issue by vaygr** [hvisage/metalog#20]
Hello,

I recently built the latest version of metalog on Alpine, and noticed it added `_` character at the end of each log line. This breaks sshguard parser for attack detection.

I tried to drop `sanitize()` and noticed every log had an extra newline, probably the non-printable character it tried to replace.

On my older system I have metalog 3 installed (2012 or so) and there's no such issue.

Curious about your thoughts on this.

**Comment by m-kress** [comment]
Is that the case with all log entries or just for logs comming from specific programs?

**Comment by vaygr** [comment]
All log entries. The workaround I have for now is this, but obviously it's not a solution as I don't quite get where it's coming from in the first place:

```diff
--- a/src/metalog.c.orig
+++ b/src/metalog.c
@@ -1303,6 +1303,8 @@
     char *info;

     sanitize(buf);
+    // drop last newline replacement
+    buf[strlen(buf)-1] = '\0';
     if (parseLogLine(loglinetype, buf, &logcode, &prg, &info) < 0)
       return -1;
     return processLogLine(logcode, prg, info);
```

**Comment by m-kress** [comment]
Could you print the last character of the line with a print() just for debugging purposes and start metalog in the foreground:
print(" 0x%x", buf[strlen(buf)-1])
Eventually it's \r or something like that?

**Comment by vaygr** [comment]
Yeah, it's `0xa`, which is `\n`.

**Comment by vaygr** [comment]
Yeah, there's nothing unusual, the previous character is the last before trailing newline.

And no, we don't enter `if (line[line_size - 1] == '\n') {`

**Comment by vaygr** [comment]
I just went through the code and it seems `parseLine()` is used only in the config parser?

**Comment by m-kress** [comment]
Yes, you are right. This though came up _after_ I pressed the send button :-)

**Comment by vaygr** [comment]
I managed to build metalog 3 on this system -- and it doesn't have this problem.

**Comment by vaygr** [comment]
Turned out it does. It just doesn't log this newline to stdout. So my assumption it's either specific to Alpine/busybox or a newer toolchain/kernel.

**Comment by m-kress** [comment]
Eventually this is related to the standard C lib you use on this. Alpine uses musl, which I never used with self compiled stuff. Is your Alpine Linux a current one or is it old?

**Comment by vaygr** [comment]
The current one.

**Comment by auouymous** [comment]
> Do you think, that metalog should remove trailing \n in any case?

It would get rid of trailing underscores for programs sending '\n' and make the logs look nicer. It would also be easy to have sanitize() strip all trailing '\n' or control codes before converting to underscores. The strlen() to find the end would however make the code less performant, unless the length is known elsewhere and could be passed to log_line().

Fetchmail is the only program I have on Gentoo that produces underscores. This could be a bigger annoyance for someone who has a lot of programs doing it. One thing to consider is that stripping the trailing newlines can break existing filters. I personally have two fetchmail filters that match the trailing underscore and would need to be changed.

But maybe one day a fetchmail update no longer produces the underscore and my filters break anyway. Having metalog strip them would make the log output a little less unstable.

**Comment by vaygr** [comment]
@m-kress yeah, I think it's a good idea. I've never seen that happening with rsyslog or syslog-ng (though this was observed on non-musl systems).

Then I took a look at the internal minimal syslogd on Alpine, and busybox [does so explicitly](https://github.com/mirror/busybox/blob/master/sysklogd/syslogd.c#L1057-L1071).

**Comment by m-kress** [comment]
I made a pull request, because also strongswan adds trailing \n to log lines.
@vaygr : could you please test this on Alpine Linux (musl)?
@auouymous : could you please test this with fetchmail?

**Comment by vaygr** [comment]
@m-kress works as expected, thank you! Let me know when you release this, so I can bump the package in Alpine.

**Comment by m-kress** [comment]
@vaygr eventually I want to look into your feature request about the import feature, but I don't know, if of when I will do it. Would you prefer a release now or rather wait until an uncertain date for the import feature?

**Comment by vaygr** [comment]
I think it's a critical fix for affected types of systems and it needs to go out ASAP.

**Comment by m-kress** [comment]
I added #22, eventually you could test this soon? Then I will make a new release.
