### ISSUE TITLE
No timestamp in command only block

### ISSUE THREAD

**Issue by pvcdx** [hvisage/metalog#5]
Hello,

it seems that metalog doesn't send timestamp to a log command if only the command is specified and not an logfile.

Example partial config:

console logging :
  facility = "*"
  command  = "/usr/local/sbin/consolelog.sh"

The consolelog script will receive first argument empty. On the other hand, for this config:

console logging :
  facility = "*"
  command  = "/usr/local/sbin/consolelog.sh"
  logdir   = "/var/log/consolelog"

Metalog calls tthe consolelog script with first argument filled out.

Could You please fix this minor bug?

Thank You.

**Comment by m-kress** [comment]
Fixing this seems to require quite some work. As a workaround you could try to use
logdir = "NONE" 
additionally to the command.

**Comment by pvcdx** [comment]
Thank You, the workaround solves this issue.
